In [63]:
import os, sys
import pandas as pd
import numpy as np
#readind and preparing data ( text , label )
data=pd.read_excel('ML1b.xlsx', header=None) ## read le file
data.columns=['label','text']
print(data[1:5])

   label                                               text
1      0  محضر تحقيق بادعاء المدعوة اسما هدى انيس قساطلي...
2      1  محضر تحقيق بحق المدعو ماهر صالح الحرامي سوري ل...
3      0  محضر بتنفيذ خلاصة حكم بحق المدعو محمد سعد الدي...
4      0  محضر بتنفيذ قرار جزائي بحق المدعو محمد سعد الد...


In [64]:
Xtb=data['text']
#X_train=Xt[0:5000]
#print(X_train[1])
Ytb=data['label']
#Y_train=Yt[0:5000]
##print(Y_train[1])
#X_test=Xt[5001:]
#Y_test=Yt[5001:]


In [20]:
# -*- coding: utf-8 -*-

# Arabic Transliteration based on Buckwalter
# dictionary source is buckwalter2unicode.py http://www.redhat.com/archives/fedora-extras-commits/2007-June/msg03617.html 

buck2uni = {"'": u"\u0621", # hamza-on-the-line
            "|": u"\u0622", # madda
            ">": u"\u0623", # hamza-on-'alif
            "&": u"\u0624", # hamza-on-waaw
            "<": u"\u0625", # hamza-under-'alif
            "}": u"\u0626", # hamza-on-yaa'
            "A": u"\u0627", # bare 'alif
            "b": u"\u0628", # baa'
            "p": u"\u0629", # taa' marbuuTa
            "t": u"\u062A", # taa'
            "v": u"\u062B", # thaa'
            "j": u"\u062C", # jiim
            "H": u"\u062D", # Haa'
            "x": u"\u062E", # khaa'
            "d": u"\u062F", # daal
            "*": u"\u0630", # dhaal
            "r": u"\u0631", # raa'
            "z": u"\u0632", # zaay
            "s": u"\u0633", # siin
            "$": u"\u0634", # shiin
            "S": u"\u0635", # Saad
            "D": u"\u0636", # Daad
            "T": u"\u0637", # Taa'
            "Z": u"\u0638", # Zaa' (DHaa')
            "E": u"\u0639", # cayn
            "g": u"\u063A", # ghayn
            "_": u"\u0640", # taTwiil
            "f": u"\u0641", # faa'
            "q": u"\u0642", # qaaf
            "k": u"\u0643", # kaaf
            "l": u"\u0644", # laam
            "m": u"\u0645", # miim
            "n": u"\u0646", # nuun
            "h": u"\u0647", # haa'
            "w": u"\u0648", # waaw
            "Y": u"\u0649", # 'alif maqSuura
            "y": u"\u064A", # yaa'
            "F": u"\u064B", # fatHatayn
            "N": u"\u064C", # Dammatayn
            "K": u"\u064D", # kasratayn
            "a": u"\u064E", # fatHa
            "u": u"\u064F", # Damma
            "i": u"\u0650", # kasra
            "~": u"\u0651", # shaddah
            "o": u"\u0652", # sukuun
            "`": u"\u0670", # dagger 'alif
            "{": u"\u0671", # waSla
}
def transString(string, reverse=0):
    '''Given a Unicode string, transliterate into Buckwalter. To go from
    Buckwalter back to Unicode, set reverse=1'''

    for k, v in buck2uni.items():
      if not reverse:
            string = string.replace(v, k)
      else:
            string = string.replace(k, v)

    return string


In [21]:
for i in range(len(Xtb)):
    Xb[i]=transString(Xtb[i])


AttributeError: 'numpy.int64' object has no attribute 'replace'

In [13]:
len(Xt)
print(data['text'][8])
print(Xt[8])

mHDr tHqyq bAdEA' fwAz mHmd Abw Emr/ lbnAny Dd mjhwlyn bjrm srqp bwAsTp Alksr wAlxlE. 
mHDr tHqyq bAdEA' fwAz mHmd Abw Emr/ lbnAny Dd mjhwlyn bjrm srqp bwAsTp Alksr wAlxlE. 


In [11]:
from snowballstemmer import stemmer
import nltk
nltk.download('stopwords')
SW=set(stopwords.words('english'))
#ar_stemmer = stemmer("arabic")
#ar_stemmer.stemWord(u"فسميتموها")
def prep(doc):
    words=str(doc).strip().split()###  strip pr eliminer les white spaces, lower por transformer en miniscules
    #stemmer=SnowballStemmer("arabic")
    #ar_stemmer = stemmer("arabic")
    #words=ar_stemmer.stem(w.decode('UTF-8'))
    words=[stemmer.stem(w) for w in words  if not w in SW]## transformer en stem without les stopwords
    return ' '.join(words)## met des spaces entre les mots
xt=Xt.apply(prep)#### select le colomn text selement et la preper(prep)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Maya\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


NameError: name 'stopwords' is not defined

In [15]:
def prep(doc):
    words=str(doc).strip().split()
    return ''.join(words)
XT=Xt.apply(prep)

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
model1=TfidfVectorizer()
tfidf_matrix=model1.fit_transform(XT)

In [18]:
from sklearn.model_selection import train_test_split

labels=data['label']
train,test,ltrain,ltest =\
train_test_split(tfidf_matrix, labels,test_size=0.2)


In [20]:

from sklearn.neural_network import MLPClassifier

mlp=MLPClassifier(hidden_layer_sizes=(50,30,), max_iter=120, solver='adam',verbose =10 , tol=1e-4, random_state=2, learning_rate_init=0.1)
model=mlp.fit(train.todense(),ltrain)

Iteration 1, loss = 2.10071537
Iteration 2, loss = 1.41568510
Iteration 3, loss = 0.87649561
Iteration 4, loss = 0.54118995
Iteration 5, loss = 0.36983646
Iteration 6, loss = 0.27539956
Iteration 7, loss = 0.19484270
Iteration 8, loss = 0.16269285
Iteration 9, loss = 0.16689769
Iteration 10, loss = 0.15249663
Iteration 11, loss = 0.14887979
Iteration 12, loss = 0.13974364
Iteration 13, loss = 0.13645701
Iteration 14, loss = 0.12231139
Iteration 15, loss = 0.12030324
Iteration 16, loss = 0.13419733
Iteration 17, loss = 0.14809884
Iteration 18, loss = 0.21203003
Iteration 19, loss = 0.26580160
Iteration 20, loss = 0.27561326
Iteration 21, loss = 0.31295914
Iteration 22, loss = 0.27506503
Iteration 23, loss = 0.25585115
Iteration 24, loss = 0.20318597
Iteration 25, loss = 0.18493851
Iteration 26, loss = 0.18097808
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.


In [21]:
from sklearn import metrics
prediction=mlp.predict(test)
cm=metrics.confusion_matrix(ltest,prediction)
print('confusion matrix is:')
print(cm)
print()
print('classification_report is:')
print(metrics.classification_report(ltest, prediction))#ngram(1,2 without to dense)
print("train Accuracy: %f" %mlp.score(train,ltrain))
print("test Accuracy: %f" %mlp.score(test,ltest))

confusion matrix is:
[[ 25   0   1   0   0   2  11  14   3   4   0   0   5]
 [ 10   1   1   1   2   9   0   0  15   9   0   0  10]
 [ 10   2  33   0   0   3   0   0   9  12   3   0   5]
 [  9   1   2  15   1  11   0   0  10  14   0   0  10]
 [  7   2   0   1  12  26   0   0  14   9   0   6  17]
 [  9   1   0   8   4  17   0   2  20  15   2   1  13]
 [ 45   0   1   0   0   0  23  32   0   1   0   0   0]
 [ 60   0   0   0   0   0   0  47   0   0   0   0   0]
 [ 13   0   2   0   0   3   0   1  65  11   0   0  12]
 [ 19   0   2   7   0   2   0   2  23  42   2   0  24]
 [125   0   1   3   0   1   0  10   0   4  15   0   1]
 [ 14   4   2   0   5   7   0   0   3   2   0 155   5]
 [ 31   9   5   1   2  28   0   1  50  24   3   3  37]]

classification_report is:
              precision    recall  f1-score   support

           1       0.07      0.38      0.11        65
           2       0.05      0.02      0.03        58
           3       0.66      0.43      0.52        77
           4       

In [22]:
#ngram(1,2 without to dense)
print("train Accuracy: %f" %mlp.score(train,ltrain))
print("test Accuracy: %f" %mlp.score(test,ltest))

train Accuracy: 0.975833
test Accuracy: 0.336094


In [65]:
#import os, sys
#import pandas as pd
#import numpy as np
#from sklearn.metrics.pairwise import cosine_similarity
#from sklearn.feature_extraction.text import TfidfVectorizer
#from sklearn.model_selection import train_test_split
#from sklearn.naive_bayes import BernoulliNB
#from sklearn.ensemble import RandomForestClassifier
##from sklearn.metrics import roc_curve, auc
#from sklearn import svm
#from sklearn.metrics import classification_report, confusion_matrix
#from sklearn.model_selection import GridSearchCV
from gensim.models import KeyedVectors
#from scipy import spatial
#import matplotlib.pyplot as plt
#from sklearn.neural_network import MLPClassifier
from nltk import bigrams
import nltk
import re
#import spacy
###FUNCTIONS
def avg_feature_vector(sentence, model, num_features, index2word_set):
        words = sentence.split()
        feature_vec = np.zeros((num_features, ), dtype='float32')
        n_words = 0
        for word in words:
            if word in index2word_set:
                n_words += 1
                feature_vec = np.add(feature_vec, model[word])
        if (n_words > 0):
            feature_vec = np.divide(feature_vec, n_words)
        return feature_vec

def convert_word2vec(sentences,num_features):
        vectors_matrix = np.zeros((len(sentences),num_features))
        i = 0
        for sent in sentences:
            temp = avg_feature_vector(sent,word2vec_vectors,num_features,index2word_set)
            vectors_matrix[i,:] = temp
            i = i+1
        return vectors_matrix
def cleaning(doc):
    # Lemmatizes and removes stopwords
    # doc needs to be a spacy Doc object
    #txt = [token for token in doc ]
    words=str(doc).strip().split()
    #words=[st.stem(w) for w in words ]
    return ' '.join(words)
    # Word2Vec uses context words to learn the vector representation of a target word,
    # if a sentence is only one or two words long,
    # the benefit for the training is very small
    #if len(txt) > 2:
      #return ' '.join(txt)
#from gensim.models.phrases import Phrases, Phraser
#data=pd.read_excel('ml2.xlsx', header=None) ## read le file
#data.columns=['text','label']
#def prep(doc):
 #   words=str(doc).strip().split()
  #  return ' '.join(words)
#Xt=Xt.apply(prep)
#sentences = Xt
data=Xtb
#data = data[data['Semantic_Type']!='DISREGARD']
#from gensim.models.phrases import Phrases, Phraser
#from nltk.stem import ISRIStemmer
#st=ISRIStemmer()
brief_cleaning = (re.sub("[^A-Za-z']+", ' ', str(row)).lower() for row in data)
txt = [cleaning(doc) for doc in data]
df_clean = pd.DataFrame({'clean': txt})
df_clean = df_clean.dropna().drop_duplicates()
df_clean.shape
sent = [row.split() for row in df_clean['clean']]
sentences = sent
from gensim.models import Word2Vec
word2vec_vectors = Word2Vec(min_count=2,window=5,size=200,sample=6e-5,alpha=0.03,min_alpha=0.0007,negative=20)
word2vec_vectors.build_vocab(sentences)
word2vec_vectors.train(sentences, total_examples=word2vec_vectors.corpus_count, epochs=30, report_delay=1)
word2vec_vectors.init_sims(replace=True)
index2word_set = set(word2vec_vectors.wv.index2word)
###vectorizing the sentences
#vectors_matrix = convert_word2vec(data['Sentence'],200)
#np.random.seed(10)
#labels=data['label']
#train,test,ltrain,ltest =train_test_split(vectors_matrix, labels,test_size=0.2)#,random_state=8)

C:\Users\Maya\Anaconda3\lib\site-packages\gensim\models\base_any2vec.py:743: UserWarning: C extension not loaded, training will be slow. Install a C compiler and reinstall gensim for fast training.
  "C extension not loaded, training will be slow. "


In [99]:
t_model = word2vec_vectors
pos_tokens=[ clean_str(t.strip()).replace(" ", "_") for t in ['شك دون رصيد', 'سلاح حربي'] if t.strip() != ""]
neg_tokens=[ clean_str(t.strip()).replace(" ", "_") for t in ['موقوف'] if t.strip() != ""]

vec = calc_vec(pos_tokens=pos_tokens, neg_tokens=neg_tokens, n_model=t_model, dim=t_model.vector_size)

most_sims = t_model.wv.similar_by_vector(vec, topn=10)
for term, score in most_sims:
    if term not in pos_tokens+neg_tokens:
        print(term, score)


صيد 0.9998825788497925
حلاوي 0.9998754858970642
الساتر 0.9998711347579956
لبنانين 0.9998612403869629
علام 0.9998611211776733
اللبان 0.9998595118522644
بسبب 0.9998589754104614
بندقية 0.999858021736145
الضرب 0.9998571276664734
خلع 0.9998557567596436


In [98]:
#python 3.X
token = clean_str(u'نشل')
# python 2.7
# token = clean_str('تونس'.decode('utf8', errors='ignore'))

most_similar = t_model.wv.most_similar( token, topn=100 )
for term, score in most_similar:
    print(term, score)


مجهولة 0.9997663497924805
اقدم 0.9997431039810181
نارية 0.9996970891952515
متن 0.9995927810668945
دراجة 0.9994726777076721
على 0.9993910789489746
المواصفات 0.9993548393249512
صغيرة 0.9992062449455261
الخليوي 0.9989694356918335
هاتفه 0.998902440071106
مجهولان 0.9987654685974121
الحجم 0.9986586570739746
نوع 0.9980621337890625
شخص 0.9978218674659729
الاقدام 0.9974756240844727
سامسونغ 0.99730384349823
لون 0.9972778558731079
هاتفها 0.9972022771835327
هاتف 0.9970158338546753
اثناء 0.9969624280929565
الساعة 0.9968664646148682
جادة 0.9968240261077881
في 0.9966819286346436
سيرا 0.9966714382171631
فر 0.9963237643241882
الى 0.996174156665802
جهة 0.9961203336715698
حوالي 0.9961131811141968
اسود 0.9960875511169434
الطيونة 0.995947003364563
من 0.9959264993667603
ايفون 0.9958641529083252
باتجاه 0.9957720637321472
التعرف 0.9957240223884583
محلة 0.995665431022644
ضد 0.9953701496124268
خليوي 0.9952776432037354
لا 0.9949822425842285
مجهولين 0.9949564933776855
المقدم 0.9948563575744629
الفوري 0.9948371052

In [71]:
def clean_str(text):
    search = ["أ","إ","آ","ة","_","-","/",".","،"," و "," يا ",'"',"ـ","'","ى","\\",'\n', '\t','&quot;','?','؟','!']
    replace = ["ا","ا","ا","ه"," "," ","","",""," و"," يا","","","","ي","",' ', ' ',' ',' ? ',' ؟ ',' ! ']
    
    #remove tashkeel
    p_tashkeel = re.compile(r'[\u0617-\u061A\u064B-\u0652]')
    text = re.sub(p_tashkeel,"", text)
    
    #remove longation
    p_longation = re.compile(r'(.)\1+')
    subst = r"\1\1"
    text = re.sub(p_longation, subst, text)
    
    text = text.replace('وو', 'و')
    text = text.replace('يي', 'ي')
    text = text.replace('اا', 'ا')
    
    for i in range(0, len(search)):
        text = text.replace(search[i], replace[i])
    
    #trim    
    text = text.strip()

    return text
def get_vec(n_model,dim, token):
    vec = np.zeros(dim)
    is_vec = False
    if token not in n_model.wv:
        _count = 0
        is_vec = True
        for w in token.split("_"):
            if w in n_model.wv:
                _count += 1
                vec += n_model.wv[w]
        if _count > 0:
            vec = vec / _count
    else:
        vec = n_model.wv[token]
    return vec

def calc_vec(pos_tokens, neg_tokens, n_model, dim):
    vec = np.zeros(dim)
    for p in pos_tokens:
        vec += get_vec(n_model,dim,p)
    for n in neg_tokens:
        vec -= get_vec(n_model,dim,n)
    
    return vec   


In [38]:
print(sent[1])
print(df_clean['clean'][1])
#print(index2word_set)

['محضر', 'تحقيق', 'بادعاء', 'المدعوة', 'اسما', 'هدى', 'انيس', 'قساطلي', 'لبنانية', 'بحق', 'مجهول', 'بموضوع', 'فقدان', 'محفظة', 'تحتوي', 'بطاقة', 'هوية', 'و', 'مبلغ', 'مالي', '.']
محضر تحقيق بادعاء المدعوة اسما هدى انيس قساطلي لبنانية بحق مجهول بموضوع فقدان محفظة تحتوي بطاقة هوية و مبلغ مالي .


In [66]:
Vectors_matrix = convert_word2vec(str(Xtb), 200)
np.random.seed(10)
#labels=Yt
#train,test,ltrain,ltest =train_test_split(vectors_matrix, labels,test_size=0.2)#,random_state=8)

C:\Users\Maya\Anaconda3\lib\site-packages\ipykernel_launcher.py:29: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).


In [31]:
print(vectors_matrix[10])

[ 3.19547369e-03  5.82107157e-03 -3.37295979e-02  2.58115376e-03
 -5.45239747e-02 -1.11295097e-02  2.23629288e-02 -9.70533639e-02
  5.43381870e-02  1.15961693e-01 -1.67765290e-01  6.15069270e-02
  9.10789445e-02 -6.18498735e-02  1.28274396e-01 -1.32828997e-02
 -4.23808135e-02  5.98876849e-02 -1.68288082e-01 -6.40497496e-03
  4.03265283e-02 -5.34946984e-03 -1.20958947e-02  1.27212465e-01
 -2.70150192e-02  5.80591895e-03 -8.85659307e-02  3.66403833e-02
  7.43004084e-02  2.79699396e-02 -6.99312687e-02  7.49559104e-02
 -2.35138517e-02 -1.46704212e-01  7.79712871e-02  3.86479683e-02
 -9.15474743e-02  1.18426129e-03  1.00725638e-02  1.45641640e-01
  9.51596797e-02  1.49067804e-01 -4.20593619e-02 -1.46789134e-01
  1.11378260e-01  4.12388965e-02 -1.62494816e-02  6.38975054e-02
 -1.28784731e-01  3.79103459e-02 -4.01398055e-02  1.58800872e-03
  1.82550922e-02 -1.32319018e-01 -4.35764156e-02  9.50044841e-02
 -1.70010403e-01 -2.86953803e-02  2.02054717e-02  2.56861318e-02
 -1.01169966e-01 -4.16843

In [46]:
print(vectors_matrix[30])

[-0.11576431 -0.01002609 -0.03963389 -0.02863568 -0.10128719  0.00106025
 -0.09017426 -0.05331455 -0.0419889  -0.13812898  0.09951101 -0.0381453
 -0.01462054 -0.01923087 -0.08817789 -0.08783196  0.03045108 -0.04160171
 -0.08114232 -0.04087094  0.08253521  0.0815117   0.02126598 -0.01539329
 -0.00369903  0.03524168 -0.07055686 -0.006049   -0.01524615 -0.02146595
  0.00159274  0.01183337  0.11407945 -0.10491984  0.03131336  0.03921975
  0.11588425  0.02416547  0.01223431 -0.01914342  0.0303671   0.02794879
  0.02775425 -0.01011413  0.02901007 -0.20301579  0.01415297  0.04110276
 -0.06836757  0.10523292 -0.04657363  0.00712253 -0.00623632 -0.08992033
 -0.15616646 -0.0813691   0.13406484 -0.06534479  0.07766499  0.07123289
 -0.04893962  0.00060352  0.02425328 -0.01052863 -0.00402694  0.0987502
 -0.03591302 -0.09796246  0.0273818   0.01614556 -0.05893252  0.00161612
 -0.03223323 -0.01235233 -0.05164547 -0.04085043 -0.04236106  0.01887214
 -0.08769996  0.10979282 -0.03733867  0.06459425  0.0

In [68]:
X_train=vectors_matrix[10:5000]
#print(X_train[1])
Y_train=Ytb[10:5000]
#print(Y_train[10])
X_test=vectors_matrix[5001:]
Y_test=Ytb[5001:]
#print(X_test[10])
#print(Y_test[5001])

In [67]:
from sklearn.model_selection import train_test_split
labels=Ytb
train,test,ltrain,ltest =train_test_split(Vectors_matrix, labels,test_size=0.2)#,random_state=8)

ValueError: Found input variables with inconsistent numbers of samples: [3577, 1980]

In [62]:
from sklearn.neural_network import MLPClassifier

mlp=MLPClassifier(hidden_layer_sizes=(50,30,), max_iter=150, solver='adam',verbose =10 , tol=1e-4, random_state=2, learning_rate_init=0.01)
model=mlp.fit(X_train,Y_train)

ValueError: Found array with dim 7. Estimator expected <= 2.

In [35]:
print("train Accuracy: %f" %mlp.score(X_train,Y_train))
print("test Accuracy: %f" %mlp.score(X_test,Y_test))

train Accuracy: 0.000000
test Accuracy: 0.000000
